# Generated by Django 5.1.1 on 2024-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewIDApplicationModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('manifest', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('headshot', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('fingerprint', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
