# Generated by Django 5.1.1 on 2024-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0003_newidapplicationmodelform'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCorrectionModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('reason', models.TextField()),
            ],
        ),
    ]
