# Generated by Django 5.1.1 on 2024-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0004_statuscorrectionmodelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscorrectionmodelform',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
