# Generated by Django 5.1.1 on 2024-10-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0005_statuscorrectionmodelform_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscorrectionmodelform',
            old_name='name',
            new_name='user_name',
        ),
    ]
