# Generated by Django 5.1.1 on 2024-10-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0006_rename_name_statuscorrectionmodelform_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscorrectionmodelform',
            old_name='old_id',
            new_name='user_id',
        ),
    ]
