# Generated by Django 5.1.1 on 2024-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0007_rename_old_id_statuscorrectionmodelform_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostIDReapplicationModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('police_abstract', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
