# Generated by Django 5.1.1 on 2024-10-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0008_lostidreapplicationmodelform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaintForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('individual_no', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUsForm',
        ),
    ]
