# Generated by Django 5.1.1 on 2024-10-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0009_usercomplaintform_delete_contactusform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscorrectionmodelform',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
