# Generated by Django 5.1.1 on 2024-10-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0010_alter_statuscorrectionmodelform_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomplaintform',
            name='phone',
        ),
    ]
