# Generated by Django 5.1.1 on 2024-10-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0011_remove_usercomplaintform_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newidapplicationmodelform',
            name='individual_no',
        ),
        migrations.RemoveField(
            model_name='newidapplicationmodelform',
            name='nationality',
        ),
    ]
