# Generated by Django 5.1.1 on 2024-10-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0012_remove_newidapplicationmodelform_individual_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPrintModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('registration_no', models.IntegerField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
