# Generated by Django 5.1.1 on 2024-10-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0013_fingerprintmodelform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprintmodelform',
            old_name='reason',
            new_name='user_reason',
        ),
    ]
