# Generated by Django 5.1.2 on 2024-10-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0014_rename_reason_fingerprintmodelform_user_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newidapplicationmodelform',
            old_name='name',
            new_name='full_name',
        ),
    ]
