# Generated by Django 5.1.2 on 2024-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0015_rename_name_newidapplicationmodelform_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newidapplicationmodelform',
            name='manifest',
            field=models.ImageField(default='default.jpg', error_messages={'required': 'Please upload file'}, upload_to='profile_pics'),
        ),
    ]
