# Generated by Django 5.1.2 on 2024-11-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0016_alter_newidapplicationmodelform_manifest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscorrectionmodelform',
            old_name='user_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='statuscorrectionmodelform',
            old_name='user_id',
            new_name='id_card',
        ),
    ]
