# Generated by Django 5.1.2 on 2024-11-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0017_rename_user_name_statuscorrectionmodelform_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprintmodelform',
            old_name='user_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='fingerprintmodelform',
            old_name='registration_no',
            new_name='individual_no',
        ),
        migrations.RenameField(
            model_name='lostidreapplicationmodelform',
            old_name='username',
            new_name='full_name',
        ),
    ]
