# Generated by Django 5.1.2 on 2024-11-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0018_rename_user_name_fingerprintmodelform_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprintmodelform',
            old_name='user_reason',
            new_name='message',
        ),
    ]
