# Generated by Django 5.1.2 on 2024-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0019_rename_user_reason_fingerprintmodelform_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewIDModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('expired_id', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
