# Generated by Django 5.1.2 on 2024-11-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_my_docs', '0020_renewidmodelform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newidapplicationmodelform',
            name='fingerprint',
            field=models.ImageField(default='default.jpg', error_messages={'required': 'Please upload your fingerprint.'}, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='newidapplicationmodelform',
            name='headshot',
            field=models.ImageField(default='default.jpg', error_messages={'required': 'Please upload your headshot.'}, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='newidapplicationmodelform',
            name='manifest',
            field=models.ImageField(default='default.jpg', error_messages={'required': 'Please upload the manifest file.'}, upload_to='profile_pics'),
        ),
    ]
